### ISSUE TITLE
Item-Difficulty-Aware Learning Path Recommendation: From a Real Walking Perspective

### ISSUE THREAD

**Issue by Advenoou** [sosweetzhang/IDALPR#1]
请问这个代码中HGNN，图的嵌入部分是怎么实现的？我看到get_graph_embeddings函数是直接加载嵌入KSSGraphEmbedding.npy，但是这个是通过什么方法得到的呢？

**Comment by qqliang** [comment]
@Advenoou 你好，请问你又找到HGNN得到graph embedding部分的代码吗？

**Comment by wxs777** [comment]
> 请问这个代码中HGNN，图的嵌入部分是怎么实现的？我看到get_graph_embeddings函数是直接加载嵌入KSSGraphEmbedding.npy，但是这个是通过什么方法得到的呢？

请问你找到了嘛？

**Comment by qqliang** [comment]
> > 请问这个代码中HGNN，图的嵌入部分是怎么实现的？我看到get_graph_embeddings函数是直接加载嵌入KSSGraphEmbedding.npy，但是这个是通过什么方法得到的呢？
> 
> 请问你找到了嘛？

没有找到
